// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Swashbuckle.AutorestExtensions.NetFramework.Example.Client
{
    using Newtonsoft.Json;
    using Swashbuckle.AutorestExtensions;
    using Swashbuckle.AutorestExtensions.NetFramework;
    using Swashbuckle.AutorestExtensions.NetFramework.Example;

    /// <summary>
    /// </summary>
    public partial interface IWebApi : System.IDisposable
    {
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        System.Uri BaseUri { get; set; }

        /// <summary>
        /// Gets or sets json serialization settings.
        /// </summary>
        JsonSerializerSettings SerializationSettings { get; }

        /// <summary>
        /// Gets or sets json deserialization settings.
        /// </summary>
        JsonSerializerSettings DeserializationSettings { get; }


        /// <summary>
        /// Gets the IStringModel.
        /// </summary>
        IStringModel StringModel { get; }

    }
}
